# Generated by Django 4.0.4 on 2022-06-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0004_alter_image_options_follow_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comment',
        ),
    ]
